### ISSUE TITLE
[新功能建议]: 取消LuckPerms的强依赖

### ISSUE THREAD

**Issue by huanmeng-qwq** [FloraCore/FloraCore#10]
### 联系方式

huanmeng@huanmeng-qwq.com

### 简明扼要地描述该建议是什么

RT，建议取消LuckPerms的强依赖
LuckPerms并不足以达到每个服务器都必须安装的必要，建议修改为软依赖，并添加接口予以默认实现，在启动时如果找到且未被设置实现实例则自动使用相关的实现类

### 实现步骤

# 

### 用户协议

- [X] 我同意遵守FloraCore的用户协议。

**Comment by xLikeWATCHDOG** [comment]
LuckPerms在此插件的作用主要实现在**跨服判断权限**。
此插件在大部分情况应当是属于**BC和Bukkit共同工作**的
就算未设置BC版本，那也应当会**有部分功能被删除**。例如Report，各种聊天等。
其实我们大抵是要考虑BC跨BC，多BC的数据同步情况。有一个跨服（BC）的权限判定是很有必要的。
如果想要去除LuckPerms的强制依赖，那么就要意味着要**开放新接口**，给予其它类似的（称号，权限）的新判定或新设置。
这似乎是提高了FC的自定义性。
**该功能将在未来的几个版本中得到更新。
感谢您的提议。**

**Comment by xLikeWATCHDOG** [comment]
该功能已经在[7a02d53](https://github.com/FloraCore/FloraCore/commit/7a02d53da05c5102341bea4b94d77f8e10fd9632)中更新，
