### ISSUE TITLE
[新功能建议]: Karma 人品值 基于部分情况的一些娱乐性质的数值数据或信任等级之类的

### ISSUE THREAD

**Issue by Shizoukia** [FloraCore/FloraCore#11]
### 联系方式

1955248991@qq.com

### 简明扼要地描述该建议是什么

例如 Hypixel 的 Karma 系统 可以在插件内部建立一种类似的交互性排名等 例如展现这个玩家的品质等等
可以实现例如
若玩家受到惩罚 扣除一定人品值
根据玩家做出的行为贡献 添加一定的人品值
人品值可以算作一种类似的或者变种的体现玩家活跃度以及信任程度的象征

*当然要做好免责声明以免担责(例如某些玩家人品值很高但是可能会利用人品值来做诈骗等行为 使用方应做好可能存在的风险)

### 实现步骤

使用litebansapi等检测处罚进行执行扣除等操作
调用已存在的小游戏api进行增加操作
例如游戏结束后发送GG或其他赞扬对手的话语可以增加人品值 反之(辱骂对手 恶意游戏行为)则扣除
其他玩家的打赏 也可以提高此玩家的信誉值/人品值

插件方面实现
小游戏API的调用检测
聊天的关键词检测
惩罚系统的API检测
注册命令用于玩家/管理员操作
数据库存储等等

### 用户协议

- [X] 我同意遵守FloraCore的用户协议。

**Comment by xLikeWATCHDOG** [comment]
FloraCore只能提供一个类似的功能和排行榜功能，但是无法做到适配各种插件，这个义务不在我们。我们也不会特意去适配，因为这是麻烦的。除非是必要情况，否则适配各种插件是不好做到的。你可以了解一下拓展功能？
