### ISSUE TITLE
[BUG]: Nick BUG

### ISSUE THREAD

**Issue by xLikeWATCHDOG** [FloraCore/FloraCore#13]
### 联系方式

bilibili.mer@outlook.com

### 简明扼要地描述该错误是什么

在部分客户端中，玩家B(使用这个客户端)的视角看玩家A，即使玩家A已经Nick了，玩家A的name tag依旧是旧名称。
Nick的修改名字的代码如下：
https://github.com/FloraCore/FloraCore/blob/3dd9b605cf6433efca047121bdabe5e4ed61bed5/bukkit/src/main/java/team/floracore/bukkit/commands/player/NickCommand.java#L191-L222
基本原理就是通过NMS修改玩家的GameProfile里的name（这个name是一个字段，final标记的）不修改UUID。
这样可以理论适配各种插件。
但是对于客户端的设置似乎无能为力？但是如果这样的话，岂不是能破解各个服务器的Nick（包括Hypixel）？
那既然这样的话，（我不认为Hypixel的Nick能获取）Nick就失去了其原本的意义了。
所以应当怎么去改，怎么去写，才能完美去适配各个端呢？
难道要将BungeeCord的name字段也改了吗？那这样的话，又会发生什么不可控的事情呢？例如，玩家进入子服务器，是以什么名字进入的呢？那对于子服来说，就似乎不能更新玩家最新昵称了？这样需要另外做出修改吗？
这似乎是一个很奇怪的问题。
但却是后续不可避免的问题。

### FloraCore版本

2.0.4.10

### 服务器类型

Paper/Bukkit

### 复现步骤

1.加入插件，Bukkit版本即可。
2.玩家A使用命令/nick。
3.启动客户端例如[cm-pack](https://www.cm-pack.pl/)启动玩家B
4.在玩家B的视角看玩家A，即使玩家A已经Nick了，玩家A的name tag依旧是旧名称。

### 用户协议

- [X] 我同意遵守FloraCore的用户协议。

**Comment by xLikeWATCHDOG** [comment]
![image](https://github.com/FloraCore/FloraCore/assets/73741466/54381209-3c5e-4415-a81d-fcd19bdb9de7)
测试：在Badlion Client正常。

**Comment by huanmeng-qwq** [comment]
建议加一个数据包拦截(1.8.x举例):
PlayerInfo包中, 拿到PlayerInfoData的集合后判断各data的uuid对应的玩家是否nick, 如果nick了就把PlayerInfoData#e字段设置为null, 然后把PlayerInfoData#d字段GameProfile修改name为nick的值, 并填写对应的properties(skin的texture)信息

**Comment by xLikeWATCHDOG** [comment]
我认为还要进行一个测试，即服务器内已存在一个已nick的玩家，然后使用该端进入服务器。如果tag正常，那么是不是可以判定该tag的name原理是记录一遍name？那如果这样的话，改那个包似乎没有啥意义？
不然我不太能理解为什么badlion正常而这个端就不行。

**Comment by huanmeng-qwq** [comment]
nick的实现原理就是我上面提到playerinfo包，然后再监听scoreboard_team的players和scoreboard_score的scorename, 这两个前者是一个集合string, 其中可能包含uuid或直接传username的, 后者则是`可能`是username
需要先用Bukkit#getPlayer(UUID)或Bukkit#getPlayerExact获取是否有这个player, 如果有就说明没有nick(要不然你也获取不到), 然后再进一步判断isNick, true就把对应的值替换成nick name

**Comment by xLikeWATCHDOG** [comment]
我注意到`PacketPlayOutPlayerInfo`类中有一个子类`PlayerInfoData`。该子类具体的字段是这样的
```
        private final int b;
        private final WorldSettings.EnumGamemode c;
        private final GameProfile d;
        private final IChatBaseComponent e;
```
不懂就问:为什么要把e设置为null？

**Comment by huanmeng-qwq** [comment]
> 我注意到`PacketPlayOutPlayerInfo`类中有一个内部类`PlayerInfoData`。该子类具体的字段是这样的
> 
> ```
>         private final int b;
>         private final WorldSettings.EnumGamemode c;
>         private final GameProfile d;
>         private final IChatBaseComponent e;
> ```
> 
> 不懂就问:为什么要把e设置为null？

e对应的displayName, 需要设置为null 否则会可能会出现白名的情况

**Comment by xLikeWATCHDOG** [comment]
我进行了简单的测试，竟然成功印证了我的想法！！
之所以那个端没法适配，是因为那个端在进游戏的时候就获取玩家的名字信息。
所以在游戏内这个玩家不管怎么改变他们的名字信息，NameTag似乎都不会变了。
我的测试是这样的。
A测试：
- 玩家A先进入游戏，并Nick了。
- 玩家B再进入游戏，查看玩家A的NameTag，发现NameTag是Nick的名字。
B测试：
- 玩家B先进入游戏。
- 玩家A再进入游戏,此时玩家A以任意一种形式（自动Nick/命令Nick）后，NameTag是原先的名字。
那这种情况就算是拦截了这个包，也无用吧？

**Comment by huanmeng-qwq** [comment]
玩家已经在游戏内了, 并使用nick指令:
手动发送playerinfo remove_player包 对应的playerinfodata都填真实的数据
接着延迟1tick，执行下面的
发送respawn包
然后再发送playerinfo add_player包 对应的playerinfodata填对应nick的数据

**Comment by xLikeWATCHDOG** [comment]
我将Nick进行了如下修改。
```
        UUID uuid = player.getUniqueId();
        NmsEntityPlayer nep = WrappedObject.wrap(ObcEntity.class, player).getHandle().cast(NmsEntityPlayer.class);
        NmsEnumPlayerInfoAction removePlayer = WrappedObject.getStatic(NmsEnumPlayerInfoAction.class).REMOVE_PLAYER();
        NmsPacketPlayOutPlayerInfo removePacket = NmsPacketPlayOutPlayerInfo.newInstance(removePlayer,
                Collections.singletonList(nep.getRaw()));
        ProtocolUtil.sendPacketToAllPlayers(removePacket);
        WrappedGameProfile wgp = nep.getGameProfile();
        wgp.setName(name);
        player.setDisplayName(name);
        player.setPlayerListName(null);
        NmsEnumPlayerInfoAction addPlayer = WrappedObject.getStatic(NmsEnumPlayerInfoAction.class).ADD_PLAYER();
        NmsPacketPlayOutPlayerInfo addPacket = NmsPacketPlayOutPlayerInfo.newInstance(addPlayer,
                Collections.singletonList(nep.getRaw()));
        List<Object> playerInfoDataList = addPacket.getPlayerInfoDataList();
        Object onpid = playerInfoDataList.get(0);
        NmsPlayerInfoData npid = WrappedObject.wrap(NmsPlayerInfoData.class, onpid);
        WrappedGameProfile fakegp = WrappedGameProfile.newInstance(UUID.randomUUID(), name);
        fakegp.setProperties(wgp.getProperties());
        fakegp.setLegacy(wgp.isLegacy());
        npid.setGameProfile(wgp);
        ProtocolUtil.sendPacketToAllPlayers(addPacket);
```
1. 我构造了一个假的GameProfile，然后其中有假的UUID，但是通过API获取的UUID是不变的。希望它能够修复。
2. 结论是，在游戏内部Nick依然无效。但是有好转的是，当我Nick完成后，被数据库记录了。然后重新进入游戏，他竟然能够成功的显示NickName。
```
    @EventHandler(priority = EventPriority.LOWEST)
    public void onPlayerJoin(PlayerJoinEvent e) 
```
这个事件就是判断玩家是否Nick，如果Nick了，那就设置Nick。设置Nick和在游戏中使用/nick命令时的方法是一样的。
这是很奇怪的，不知道是哪里遗漏了。
还有一个奇怪的现象，就是我在第一次测试的时候，好像出现了2个名字？
但是后续没有复现了？
![DXH7_(_OEGZ4BD%JVZ09$@T](https://github.com/FloraCore/FloraCore/assets/73741466/bfd94c06-49cb-4bdf-92fa-1bfbe661f3b6)
我再测试一下。
直接改ep的gameprofile name，我考虑到了极少数插件使用name进行保存数据。但是如果不直接修改这个，许多的插件无法直接适配。

**Comment by xLikeWATCHDOG** [comment]
我构造了一个重生的包，看看可不可以。
```
        World world = player.getWorld();
        NmsWorldServer nmsWorldServer = WrappedObject.wrap(ObcWorld.class,world).getHandle();
        int dimension = nmsWorldServer.getDimension();
        NmsWorldData nmsWorldData = nmsWorldServer.getWorldData();
        NmsEnumDifficulty nmsEnumDifficulty = nmsWorldData.getDifficulty();
        NmsWorldType nmsWorldType = nmsWorldData.getType();
        NmsPlayerInteractManager nmsPlayerInteractManager = nep.getPlayerInteractManager();
        NmsEnumGamemode nmsEnumGamemode = nmsPlayerInteractManager.getGameMode();
        NmsPacketPlayOutRespawn respawnPacket = NmsPacketPlayOutRespawn.newInstance(dimension,nmsEnumDifficulty,nmsWorldType,nmsEnumGamemode);
        ProtocolUtil.sendPacketToAllPlayers(respawnPacket);
```

**Comment by xLikeWATCHDOG** [comment]
但是我发现 发送之后，玩家的世界可能会出现问题？
![image](https://github.com/FloraCore/FloraCore/assets/73741466/69f6527c-f7ef-428c-8981-c3946992adb7)

**Comment by huanmeng-qwq** [comment]
respawn后面调用teleport方法传送一下, 然后发送headRotation, 最后addplayer包发给全部玩家(还是自己来着 忘了)
